# Run linters automatically on pull requests.
name: Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}(${{ matrix.ros_distribution }})
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.docker_image }}
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - jazzy
          - humble
          - rolling
        include:
          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-ros-base-latest
            ros_distribution: jazzy
            ros_version: 2
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
        linter:
          - copyright
          - xmllint
          - lint_cmake
    steps:
      - uses: actions/checkout@v5
      - uses: ros-tooling/action-ros-lint@0.1.4
        with:
          linter: ${{ matrix.linter }}
          distribution: ${{ matrix.ros_distribution }}
          package-name: osqp_vendor
